language: python
python:
    - "3.6"
install:
    - pip install .
script:
    - ls /home/travis/build/rbeucher/pyFTracks/pyFTracks/
    - python -c "import pyFTracks; print('OK')"
os:
    - linux
    - osx
    - windows
