  version: '3.7'
  services:
    
    pyFTracks:
      build: 
        context: .
        dockerfile: ./Dockerfile
      container_name: pyFTracks
      image: rbeucher/pyftracks:latest
      command: "jupyter notebook --ip=0.0.0.0 --no-browser"
      ports:
        - "8888:8888"
      volumes:
        - $PWD:/opt/pyFTracks
        - $PWD/docs:/home
