  version: '3.7'
  services:
    
    pyFTracks:
      build: 
        context: .
        dockerfile: ./Dockerfile
      container_name: pyFTracks
      image: rbeucher/pyftracks:latest
      entrypoint: /bin/sh -c "while sleep 1000; do :; done"
      ports:
        - "8888:8888"
      volumes:
        - $PWD:/opt/pyFTracks
        - $PWD/docs:/home
